server:
  port: 8080

spring:
  application:
    name: TaskTrackerGraphQL

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/tasktracker}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.graphql: DEBUG



  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
    schema:
      printer:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}


